modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="silenthill"
version="3.0.0"
displayName="JS' Silent Hill"
authors="J.S.art"
description='''
Silent Hill creatures will invade your world!
'''

[[dependencies.silenthill]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,21.2)"
    ordering="NONE"
    side="BOTH"

[[dependencies.silenthill]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"
